image:
  name: docker:latest

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  services:
    - name: docker:dind
  script:
    - cd cpbr14/yii-2
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/thtmorais/campus-party:$CI_COMMIT_REF_NAME .
    - docker push registry.gitlab.com/thtmorais/campus-party:$CI_COMMIT_REF_NAME
    - docker logout $CI_REGISTRY
  only:
    - merge_requests
  interruptible: true

test-job:
  stage: test
  image: registry.gitlab.com/thtmorais/campus-party:$CI_COMMIT_REF_NAME
  script:
    - cd cpbr14/yii-2
    - composer install
    - vendor/bin/codecept run --xml --html --coverage --coverage-xml --coverage-html --coverage-cobertura
  only:
    - merge_requests
  interruptible: true

deploy-job:
  stage: deploy
  services:
    - name: docker:dind
  script:
    - cd cpbr14/yii-2
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/imuv/imuv:latest .
    - docker push registry.gitlab.com/imuv/imuv:latest
    - docker logout $CI_REGISTRY
  only:
    - main
  interruptible: true
