image:
  name: docker:latest

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  services:
    - name: docker:dind
  script:
    - echo $SENHA
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/thtmorais/campus-party:$CI_COMMIT_REF_NAME .
    - docker push registry.gitlab.com/thtmorais/campus-party:$CI_COMMIT_REF_NAME
    - docker logout $CI_REGISTRY
  only:
    - merge_requests
  interruptible: true